name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/_build.yml
